services:
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
      args:
        SCHEMA_PATH_DEMO: db/seaj-db-diagnostics.sql
        SCHEMA_PATH_DEV: db/seaj-db-perf.sql
    container_name: seaj_postgres_db
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata_volume:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: starter/Dockerfile
    container_name: seaj_app
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"

volumes:
  pgdata_volume:
