-- SEAJ OLTP schema - Master Index
-- This file orchestrates the creation of the entire database schema
-- Execute in the following order to ensure dependencies are met:
-- 1. Setup (extensions and enums)
-- 3. Accounts
-- 4. Instruments
-- 5. Orders (depends on Accounts and Instruments)
-- 6. Positions (depends on Accounts and Instruments)
-- 7. Order History (depends on Orders)
