spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SEAJ_db
    username: postgres
    password: n3u3d4!
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
